### ISSUE TITLE
Extend gitpull.sh so that it also clones new created repos but still pulls existing ones

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/reporting#5]
https://github.com/EmbeddedMontiArc/reporting/blob/943277348b7041b5381528cb2eb0e4059d086e24/gitpull.sh#L10

the script only clones all repos or none -> it should clone all new repos which have not be cloned before, all other repos should be pulled (in order to get not blocked by github)

**Comment by mh062909** [comment]
Travis is deleting the whole repo for each build. There is a option to cache directories, but they say that big files should not be cached. But I fixed this issue by excluding "external-dependencies", which was by far the biggest repository.
